
    const barangaysData = {
        "select":[
            { barangay: "", zipCode: "" },
        ],
        "Cavite City": [
            { barangay: "Barangay 1", zipCode: "4100" },
            { barangay: "Barangay 10", zipCode: "4100" },
            { barangay: "Barangay 10-A", zipCode: "4100" },
            { barangay: "Barangay 10-B", zipCode: "4100" },
            { barangay: "Barangay 11", zipCode: "4100" },
            { barangay: "Barangay 12", zipCode: "4100" },
            { barangay: "Barangay 13", zipCode: "4100" },
            { barangay: "Barangay 14", zipCode: "4100" },
            { barangay: "Barangay 15", zipCode: "4100" },
            { barangay: "Barangay 16", zipCode: "4100" },
            { barangay: "Barangay 17", zipCode: "4100" },
            { barangay: "Barangay 18", zipCode: "4100" },
            { barangay: "Barangay 19", zipCode: "4100" },
            { barangay: "Barangay 2", zipCode: "4100" },
            { barangay: "Barangay 20", zipCode: "4100" },
            { barangay: "Barangay 21", zipCode: "4100" },
            { barangay: "Barangay 22", zipCode: "4100" },
            { barangay: "Barangay 22-A", zipCode: "4100" },
            { barangay: "Barangay 23", zipCode: "4100" },
            { barangay: "Barangay 24", zipCode: "4100" },
            { barangay: "Barangay 25", zipCode: "4100" },
            { barangay: "Barangay 26", zipCode: "4100" },
            { barangay: "Barangay 27", zipCode: "4100" },
            { barangay: "Barangay 28", zipCode: "4100" },
            { barangay: "Barangay 29", zipCode: "4100" },
            { barangay: "Barangay 29-A", zipCode: "4100" },
            { barangay: "Barangay 3", zipCode: "4100" },
            { barangay: "Barangay 30", zipCode: "4100" },
            { barangay: "Barangay 31", zipCode: "4100" },
            { barangay: "Barangay 32", zipCode: "4100" },
            { barangay: "Barangay 33", zipCode: "4100" },
            { barangay: "Barangay 34", zipCode: "4100" },
            { barangay: "Barangay 35", zipCode: "4100" },
            { barangay: "Barangay 36", zipCode: "4100" },
            { barangay: "Barangay 37", zipCode: "4100" },
            { barangay: "Barangay 38", zipCode: "4100" },
            { barangay: "Barangay 39", zipCode: "4100" },
            { barangay: "Barangay 4", zipCode: "4100" },
            { barangay: "Barangay 40", zipCode: "4100" },
            { barangay: "Barangay 41", zipCode: "4100" },
            { barangay: "Barangay 42", zipCode: "4100" },
            { barangay: "Barangay 42-A", zipCode: "4100" },
            { barangay: "Barangay 42-B", zipCode: "4100" },
            { barangay: "Barangay 42-C", zipCode: "4100" },
            { barangay: "Barangay 43", zipCode: "4100" },
            { barangay: "Barangay 44", zipCode: "4100" },
            { barangay: "Barangay 45", zipCode: "4100" },
            { barangay: "Barangay 45-A", zipCode: "4100" },
            { barangay: "Barangay 46", zipCode: "4100" },
            { barangay: "Barangay 47", zipCode: "4100" },
            { barangay: "Barangay 47-A", zipCode: "4100" },
            { barangay: "Barangay 47-B", zipCode: "4100" },
            { barangay: "Barangay 48", zipCode: "4100" },
            { barangay: "Barangay 48-A", zipCode: "4100" },
            { barangay: "Barangay 49", zipCode: "4100" },
            { barangay: "Barangay 49-A", zipCode: "4100" },
            { barangay: "Barangay 5", zipCode: "4100" },
            { barangay: "Barangay 50", zipCode: "4100" },
            { barangay: "Barangay 51", zipCode: "4100" },
            { barangay: "Barangay 52", zipCode: "4100" },
            { barangay: "Barangay 53", zipCode: "4100" },
            { barangay: "Barangay 53-A", zipCode: "4100" },
            { barangay: "Barangay 53-B", zipCode: "4100" },
            { barangay: "Barangay 53-B", zipCode: "4100" },
            { barangay: "Barangay 54", zipCode: "4100" },
            { barangay: "Barangay 54-A", zipCode: "4100" },
            { barangay: "Barangay 55", zipCode: "4100" },
            { barangay: "Barangay 56", zipCode: "4100" },
            { barangay: "Barangay 57", zipCode: "4100" },
            { barangay: "Barangay 58", zipCode: "4100" },
            { barangay: "Barangay 58-A", zipCode: "4100" },
            { barangay: "Barangay 59", zipCode: "4100" },
            { barangay: "Barangay 6", zipCode: "4100" },
            { barangay: "Barangay 60", zipCode: "4100" },
            { barangay: "Barangay 61", zipCode: "4100" },
            { barangay: "Barangay 61-A", zipCode: "4100" },
            { barangay: "Barangay 62", zipCode: "4100" },
            { barangay: "Barangay 62-A", zipCode: "4100" },
            { barangay: "Barangay 62-B", zipCode: "4100" },
            { barangay: "Barangay 7", zipCode: "4100" },
            { barangay: "Barangay 8", zipCode: "4100" },
            { barangay: "Barangay 9", zipCode: "4100" },
            { barangay: "Corregidor Island", zipCode: "4125" },
            { barangay: "Sangley Point Naval Base", zipCode: "4101" },
        ],
        "Kawit, Cavite": [
            { barangay: "Binakayan", zipCode: "4104" },
            { barangay: "Balsahan-Bisita", zipCode: "4104" },
            { barangay: "Batong Dalig", zipCode: "4104" },
            { barangay: "Binakayan - Aplaya", zipCode: "4104" },
            { barangay: "Binakayan - Kanluran", zipCode: "4104" },
            { barangay: "Congbalay - Legaspi", zipCode: "4104" },
            { barangay: "Gahak", zipCode: "4104" },
            { barangay: "Kaingen", zipCode: "4104" },
            { barangay: "Magdalo", zipCode: "4104" },
            { barangay: "Manggahan - Lawin", zipCode: "4104" },
            { barangay: "Marulas", zipCode: "4104" },
            { barangay: "Panamitan", zipCode: "4104" },
            { barangay: "Poblacion", zipCode: "4104" },
            { barangay: "Pulvorista", zipCode: "4104" },
            { barangay: "Samala - Marquez", zipCode: "4104" },
            { barangay: "San Sebastian", zipCode: "4104" },
            { barangay: "Santa Isabel", zipCode: "4104" },
            { barangay: "Tabon I", zipCode: "4104" },
            { barangay: "Tabon II", zipCode: "4104" },
            { barangay: "Tabon III", zipCode: "4104" },
            { barangay: "Toclong", zipCode: "4104" },
            { barangay: "Tramo - Bantayan", zipCode: "4104" },
            { barangay: "Wakas I", zipCode: "4104" },
            { barangay: "Wakas II", zipCode: "4104" },
            // Add more barangays and zip codes for Kawit, Cavite
        ],
        "Noveleta, Cavite": [
            { barangay: "Magdiwang", zipCode: "4105" },
            { barangay: "Poblacion", zipCode: "4105" },
            { barangay: "Salcedo I", zipCode: "4105" },
            { barangay: "Salcedo II", zipCode: "4105" },
            { barangay: "San Antonio I", zipCode: "4105" },
            { barangay: "San Antonio II", zipCode: "4105" },
            { barangay: "San jose I", zipCode: "4105" },
            { barangay: "San jose II", zipCode: "4105" },
            { barangay: "San juan I", zipCode: "4105" },
            { barangay: "San juan II", zipCode: "4105" },
            { barangay: "San Rafael I", zipCode: "4105" },
            { barangay: "San Rafael II", zipCode: "4105" },
            { barangay: "San Rafael III", zipCode: "4105" },
            { barangay: "San Rafael IV", zipCode: "4105" },
            { barangay: "Santa Rosa I", zipCode: "4105" },
            { barangay: "Santa Rosa II", zipCode: "4105" },
        ],
        "Rosario, Cavite": [
            { barangay: "Bagbag I", zipCode: "4106" },
            { barangay: "Bagbag II", zipCode: "4106" },
            { barangay: "Kanluran", zipCode: "4106" },
            { barangay: "Ligtong II", zipCode: "4106" },
            { barangay: "Ligtong III", zipCode: "4106" },
            { barangay: "Ligtong IV", zipCode: "4106" },
            { barangay: "Muzon I", zipCode: "4106" },
            { barangay: "Muzon II", zipCode: "4106" },
            { barangay: "Poblacion", zipCode: "4106" },
            { barangay: "Sapa I", zipCode: "4106" },
            { barangay: "Sapa II", zipCode: "4106" },
            { barangay: "Sapa III", zipCode: "4106" },
            { barangay: "Sapa IV", zipCode: "4106" },
            { barangay: "Singalan I", zipCode: "4106" },
            { barangay: "Singalan II", zipCode: "4106" },
            { barangay: "Tejeros Convention", zipCode: "4106" },
            { barangay: "Wawa I", zipCode: "4106" },
            { barangay: "Wawa II", zipCode: "4106" },
            { barangay: "Wawa III", zipCode: "4106" },
        ],
        "Bacoor City": [
            { barangay: "Alima", zipCode: "4102" },
            { barangay: "Aniban I", zipCode: "4102" },
            { barangay: "Aniban I", zipCode: "4102" },
            { barangay: "Aniban III", zipCode: "4102" },
            { barangay: "Aniban IV", zipCode: "4102" },
            { barangay: "Aniban V", zipCode: "4102" },
            { barangay: "Banalo", zipCode: "4102" },
            { barangay: "Bayanan", zipCode: "4102" },
            { barangay: "Campo santo", zipCode: "4102" },
            { barangay: "Daang bukid", zipCode: "4102" },
            { barangay: "Digman", zipCode: "4102" },
            { barangay: "Dulong bayan", zipCode: "4102" },
            { barangay: "Habay I", zipCode: "4102" },
            { barangay: "Habay II", zipCode: "4102" },
            { barangay: "Kaingin", zipCode: "4102" },
            { barangay: "Ligas I", zipCode: "4102" },
            { barangay: "Ligas II", zipCode: "4102" },
            { barangay: "Ligas III", zipCode: "4102" },
            { barangay: "Mabolo I", zipCode: "4102" },
            { barangay: "Mabolo II", zipCode: "4102" },
            { barangay: "Mabolo III", zipCode: "4102" },
            { barangay: "Maliksi I", zipCode: "4102" },
            { barangay: "Maliksi II", zipCode: "4102" },
            { barangay: "Maliksi III", zipCode: "4102" },
            { barangay: "Mambog I", zipCode: "4102" },
            { barangay: "Mambog II", zipCode: "4102" },
            { barangay: "Mambog III", zipCode: "4102" },
            { barangay: "Mambog IV", zipCode: "4102" },
            { barangay: "Mambog V", zipCode: "4102" },
            { barangay: "Molino I", zipCode: "4102" },
            { barangay: "Molino II", zipCode: "4102" },
            { barangay: "Molino III", zipCode: "4102" },
            { barangay: "Molino IV", zipCode: "4102" },
            { barangay: "Molino V", zipCode: "4102" },
            { barangay: "Molino VI", zipCode: "4102" },
            { barangay: "Molino VII", zipCode: "4102" },
            { barangay: "Niog I", zipCode: "4102" },
            { barangay: "Niog II", zipCode: "4102" },
            { barangay: "Niog III", zipCode: "4102" },
            { barangay: "P. F. Espiritu I", zipCode: "4102" },
            { barangay: "P. F. Espiritu II", zipCode: "4102" },
            { barangay: "P. F. Espiritu III", zipCode: "4102" },
            { barangay: "P. F. Espiritu IV", zipCode: "4102" },
            { barangay: "P. F. Espiritu V", zipCode: "4102" },
            { barangay: "P. F. Espiritu VI", zipCode: "4102" },
            { barangay: "P. F. Espiritu VII", zipCode: "4102" },
            { barangay: "P. F. Espiritu VIII", zipCode: "4102" },
            { barangay: "Queens Row Central", zipCode: "4102" },
            { barangay: "Queens Row East", zipCode: "4102" },
            { barangay: "Queens Row West", zipCode: "4102" },
            { barangay: "Real I", zipCode: "4102" },
            { barangay: "Real II", zipCode: "4102" },
            { barangay: "Salinas I", zipCode: "4102" },
            { barangay: "Salinas II", zipCode: "4102" },
            { barangay: "Salinas III", zipCode: "4102" },
            { barangay: "Salinas IV", zipCode: "4102" },
            { barangay: "San Nicolas I", zipCode: "4102" },
            { barangay: "San Nicolas II", zipCode: "4102" },
            { barangay: "San Nicolas III", zipCode: "4102" },
            { barangay: "Sineguelasan", zipCode: "4102" },
            { barangay: "Tabing Dagat", zipCode: "4102" },
            { barangay: "Talaba I", zipCode: "4102" },
            { barangay: "Talaba II", zipCode: "4102" },
            { barangay: "Talaba III", zipCode: "4102" },
            { barangay: "Talaba IV", zipCode: "4102" },
            { barangay: "Talaba V", zipCode: "4102" },
            { barangay: "Talaba VI", zipCode: "4102" },
            { barangay: "Talaba VII", zipCode: "4102" },
            { barangay: "Zapote I", zipCode: "4102" },
            { barangay: "Zapote II", zipCode: "4102" },
            { barangay: "Zapote III", zipCode: "4102" },
            { barangay: "Zapote IV", zipCode: "4102" },
            { barangay: "Zapote V", zipCode: "4102" },
        ],
        "Imus City": [
            { barangay: "Alapan I-A", zipCode: "4103" },
            { barangay: "Alapan I-B", zipCode: "4103" },
            { barangay: "Alapan I-C", zipCode: "4103" },
            { barangay: "Alapan II-A", zipCode: "4103" },
            { barangay: "Alapan II-B", zipCode: "4103" },
            { barangay: "Anabu I-A", zipCode: "4103" },
            { barangay: "Anabu I-B", zipCode: "4103" },
            { barangay: "Anabu I-C", zipCode: "4103" },
            { barangay: "Anabu I-D", zipCode: "4103" },
            { barangay: "Anabu I-E", zipCode: "4103" },
            { barangay: "Anabu I-F", zipCode: "4103" },
            { barangay: "Anabu I-G", zipCode: "4103" },
            { barangay: "Anabu II-A", zipCode: "4103" },
            { barangay: "Anabu II-B", zipCode: "4103" },
            { barangay: "Anabu II-C", zipCode: "4103" },
            { barangay: "Anabu II-D", zipCode: "4103" },
            { barangay: "Anabu II-E", zipCode: "4103" },
            { barangay: "Anabu II-F", zipCode: "4103" },
            { barangay: "Bagong Silang", zipCode: "4103" },
            { barangay: "Bayan Luma I", zipCode: "4103" },
            { barangay: "Bayan Luma II", zipCode: "4103" },
            { barangay: "Bayan Luma III", zipCode: "4103" },
            { barangay: "Bayan Luma IV", zipCode: "4103" },
            { barangay: "Bayan Luma IX", zipCode: "4103" },
            { barangay: "Bayan Luma V", zipCode: "4103" },
            { barangay: "Bayan Luma VI", zipCode: "4103" },
            { barangay: "Bayan Luma VII", zipCode: "4103" },
            { barangay: "Bayan Luma VIII", zipCode: "4103" },
            { barangay: "Bucandala I", zipCode: "4103" },
            { barangay: "Bucandala II", zipCode: "4103" },
            { barangay: "Bucandala III", zipCode: "4103" },
            { barangay: "Bucandala IV", zipCode: "4103" },
            { barangay: "Bucandala V", zipCode: "4103" },
            { barangay: "Buhay na Tubig", zipCode: "4103" },
            { barangay: "Carsadang Bago I", zipCode: "4103" },
            { barangay: "Carsadang Bago II", zipCode: "4103" },
            { barangay: "Magdalo", zipCode: "4103" },
            { barangay: "Maharlika", zipCode: "4103" },
            { barangay: "Malagasang I-A", zipCode: "4103" },
            { barangay: "Malagasang I-B", zipCode: "4103" },
            { barangay: "Malagasang I-C", zipCode: "4103" },
            { barangay: "Malagasang I-D", zipCode: "4103" },
            { barangay: "Malagasang I-E", zipCode: "4103" },
            { barangay: "Malagasang I-F", zipCode: "4103" },
            { barangay: "Malagasang I-G", zipCode: "4103" },
            { barangay: "Malagasang II-A", zipCode: "4103" },
            { barangay: "Malagasang II-B", zipCode: "4103" },
            { barangay: "Malagasang II-C", zipCode: "4103" },
            { barangay: "Malagasang II-D", zipCode: "4103" },
            { barangay: "Malagasang II-E", zipCode: "4103" },
            { barangay: "Malagasang II-F", zipCode: "4103" },
            { barangay: "Malagasang II-G", zipCode: "4103" },
            { barangay: "Mariano Espeleta I", zipCode: "4103" },
            { barangay: "Mariano Espeleta II", zipCode: "4103" },
            { barangay: "Mariano Espeleta III", zipCode: "4103" },
            { barangay: "Medicion I-A", zipCode: "4103" },
            { barangay: "Medicion I-B", zipCode: "4103" },
            { barangay: "Medicion I-C", zipCode: "4103" },
            { barangay: "Medicion I-D", zipCode: "4103" },
            { barangay: "Medicion II-A", zipCode: "4103" },
            { barangay: "Medicion II-B", zipCode: "4103" },
            { barangay: "Medicion II-C", zipCode: "4103" },
            { barangay: "Medicion II-D", zipCode: "4103" },
            { barangay: "Medicion II-E", zipCode: "4103" },
            { barangay: "Medicion II-F", zipCode: "4103" },
            { barangay: "Pag-asa I", zipCode: "4103" },
            { barangay: "Pag-asa II", zipCode: "4103" },
            { barangay: "Pag-asa III", zipCode: "4103" },
            { barangay: "Palico I", zipCode: "4103" },
            { barangay: "Palico II", zipCode: "4103" },
            { barangay: "Palico III", zipCode: "4103" },
            { barangay: "Palico IV", zipCode: "4103" }, 
            { barangay: "Pasong Buaya I", zipCode: "4103" }, 
            { barangay: "Pasong Buaya II", zipCode: "4103" }, 
            { barangay: "Pinagbuklod", zipCode: "4103" }, 
            { barangay: "Poblacion I-A", zipCode: "4103" }, 
            { barangay: "Poblacion I-B", zipCode: "4103" }, 
            { barangay: "Poblacion I-C", zipCode: "4103" }, 
            { barangay: "Poblacion II-A", zipCode: "4103" }, 
            { barangay: "Poblacion II-B", zipCode: "4103" }, 
            { barangay: "Poblacion III-A", zipCode: "4103" }, 
            { barangay: "Poblacion III-B", zipCode: "4103" }, 
            { barangay: "Poblacion IV-A", zipCode: "4103" }, 
            { barangay: "Poblacion IV-B", zipCode: "4103" }, 
            { barangay: "Poblacion IV-C", zipCode: "4103" }, 
            { barangay: "Poblacion IV-D", zipCode: "4103" }, 
            { barangay: "Tanzang Luma I", zipCode: "4103" }, 
            { barangay: "Tanzang Luma II", zipCode: "4103" }, 
            { barangay: "Tanzang Luma III", zipCode: "4103" }, 
            { barangay: "Tanzang Luma IV", zipCode: "4103" }, 
            { barangay: "Tanzang Luma V", zipCode: "4103" }, 
            { barangay: "Tanzang Luma VI", zipCode: "4103" }, 
            { barangay: "Toclong I-A", zipCode: "4103" }, 
            { barangay: "Toclong I-B", zipCode: "4103" }, 
            { barangay: "Toclong I-C", zipCode: "4103" }, 
            { barangay: "Toclong II-A", zipCode: "4103" }, 
            { barangay: "Toclong II-B", zipCode: "4103" }, 
        ],
        "Dasmarinas City": [
            { barangay: "Burol", zipCode: "4114" },
            { barangay: "Burol I", zipCode: "4114" },
            { barangay: "Burol II", zipCode: "4114" },
            { barangay: "Burol III", zipCode: "4114" },
            { barangay: "Datu Esmael", zipCode: "4114" },
            { barangay: "Emmanuel Bergado I", zipCode: "4114" },
            { barangay: "Emmanuel Bergado II", zipCode: "4114" },
            { barangay: "Fatima I", zipCode: "4114" },
            { barangay: "Fatima II", zipCode: "4114" },
            { barangay: "Fatima III", zipCode: "4114" },
            { barangay: "H-2", zipCode: "4114" },
            { barangay: "Langkaan I", zipCode: "4114" },
            { barangay: "Langkaan II", zipCode: "4114" },
            { barangay: "Langkaan II", zipCode: "4114" },
            { barangay: "Luzvimida I", zipCode: "4114" },
            { barangay: "Luzvimida II", zipCode: "4114" },
            { barangay: "Paliparan I", zipCode: "4114" },
            { barangay: "Paliparan II", zipCode: "4114" },
            { barangay: "Paliparan III", zipCode: "4114" },
            { barangay: "Sabang", zipCode: "4114" },
            { barangay: "Saint Peter I", zipCode: "4114" },
            { barangay: "Saint Peter II", zipCode: "4114" },
            { barangay: "Salawag", zipCode: "4114" },
            { barangay: "Salitran I", zipCode: "4114" },
            { barangay: "Salitran II", zipCode: "4114" },
            { barangay: "Salitran III", zipCode: "4114" },
            { barangay: "Salitran IV", zipCode: "4114" },
            { barangay: "Sampaloc I", zipCode: "4114" },
            { barangay: "Sampaloc II", zipCode: "4114" },
            { barangay: "Sampaloc III", zipCode: "4114" },
            { barangay: "Sampaloc IV", zipCode: "4114" },
            { barangay: "Sampaloc V", zipCode: "4114" },
            { barangay: "San Agustin I", zipCode: "4114" },
            { barangay: "San Agustin II", zipCode: "4114" },
            { barangay: "San Agustin III", zipCode: "4114" },
            { barangay: "San Andres I", zipCode: "4114" },
            { barangay: "San Andres II", zipCode: "4114" },
            { barangay: "San Antonio de Padua I", zipCode: "4114" },
            { barangay: "San Antonio de Padua II", zipCode: "4114" },
            { barangay: "San Dionisio", zipCode: "4114" },
            { barangay: "San Esteban", zipCode: "4114" },
            { barangay: "San Francisco I", zipCode: "4114" },
            { barangay: "San Francisco II", zipCode: "4114" },
            { barangay: "San Isidro Labrador I", zipCode: "4114" },
            { barangay: "San Isidro Labrador II", zipCode: "4114" },
            { barangay: "San Jose", zipCode: "4114" },
            { barangay: "San Juan", zipCode: "4114" },
            { barangay: "San Lorenzo Ruiz I", zipCode: "4114" },
            { barangay: "San Lorenzo Ruiz II", zipCode: "4114" },
            { barangay: "San Luiz I", zipCode: "4114" },
            { barangay: "San Luiz II", zipCode: "4114" },
            { barangay: "San Manuel I", zipCode: "4114" },
            { barangay: "San Manuel II", zipCode: "4114" },
            { barangay: "San Mateo", zipCode: "4114" },
            { barangay: "San Miguel", zipCode: "4114" },
            { barangay: "San Miguel II", zipCode: "4114" },
            { barangay: "San Nicolas I", zipCode: "4114" },
            { barangay: "San Nicolas II", zipCode: "4114" },
            { barangay: "San Roque", zipCode: "4114" },
            { barangay: "San Simon", zipCode: "4114" },
            { barangay: "Santa Cristina I", zipCode: "4114" },
            { barangay: "Santa Cristina II", zipCode: "4114" },
            { barangay: "Santa Cruz I", zipCode: "4114" },
            { barangay: "Santa Cruz II", zipCode: "4114" },
            { barangay: "Santa Fe", zipCode: "4114" },
            { barangay: "Santa Lucia", zipCode: "4114" },
            { barangay: "Santa Maria", zipCode: "4114" },
            { barangay: "Santo Cristo", zipCode: "4114" },
            { barangay: "Santo Niño I", zipCode: "4114" },
            { barangay: "Santo Niño II", zipCode: "4114" },
            { barangay: "Victoria Reyes", zipCode: "4114" },
            { barangay: "Zone I", zipCode: "4114" },
            { barangay: "Zone II", zipCode: "4114" },
            { barangay: "Zone III", zipCode: "4114" },
            { barangay: "Zone IV", zipCode: "4114" },

            { barangay: "Dasmariñas Resettlement Area", zipCode: "4115" },
        ],
        "Carmona, Cavite": [
            { barangay: "Bancal", zipCode: "4116" },
            { barangay: "Barangay I", zipCode: "4116" },
            { barangay: "Barangay II", zipCode: "4116" },
            { barangay: "Barangay III", zipCode: "4116" },
            { barangay: "Barangay IV", zipCode: "4116" },
            { barangay: "Barangay V", zipCode: "4116" },
            { barangay: "Barangay VI", zipCode: "4116" },
            { barangay: "Barangay VII", zipCode: "4116" },
            { barangay: "Barangay VIII", zipCode: "4116" },
            { barangay: "Cabilang Baybay", zipCode: "4116" },
            { barangay: "Lantic", zipCode: "4116" },
            { barangay: "Mabuhay", zipCode: "4116" },
            { barangay: "Maduya", zipCode: "4116" },
            { barangay: "Milagrosa", zipCode: "4116" },
        ],
        "General Mariano Alvarez, Cavite": [
            { barangay: "Aldiano Olaes", zipCode: "4117" },
            { barangay: "Barangay 1 Poblacion", zipCode: "4117" },
            { barangay: "Barangay 2 Poblacion", zipCode: "4117" },
            { barangay: "Barangay 3 Poblacion", zipCode: "4117" },
            { barangay: "Barangay 4 Poblacion", zipCode: "4117" },
            { barangay: "Barangay 5 Poblacion", zipCode: "4117" },
            { barangay: "Benjamin Tirona", zipCode: "4117" },
            { barangay: "Bernardo Pulido", zipCode: "4117" },
            { barangay: "Epifanio Malia", zipCode: "4117" },
            { barangay: "Fiorello Calimag", zipCode: "4117" },
            { barangay: "Francesco Reyes", zipCode: "4117" },
            { barangay: "Francisco de Castro", zipCode: "4117" },
            { barangay: "Gavino Maderan", zipCode: "4117" },
            { barangay: "Gregoria de Jesus", zipCode: "4117" },
            { barangay: "Inocencio Salud", zipCode: "4117" },
            { barangay: "Jacinto Lumbreras", zipCode: "4117" },
            { barangay: "Kapitan Kua", zipCode: "4117" },
            { barangay: "Koronel Jose P. Elises", zipCode: "4117" },
            { barangay: "Macario Dacon", zipCode: "4117" },
            { barangay: "Marcelino Memije", zipCode: "4117" },
            { barangay: "Nicolasa Virata", zipCode: "4117" },
            { barangay: "Pantaleon Granados", zipCode: "4117" },
            { barangay: "Ramon Cruz", zipCode: "4117" },
            { barangay: "San Gabriel", zipCode: "4117" },
            { barangay: "San Jose", zipCode: "4117" },
            { barangay: "Severino de Las Alas", zipCode: "4117" },
            { barangay: "Tiniente Tiago", zipCode: "4117" },
        ],
        "Silang, Cavite": [
            { barangay: "Acacia", zipCode: "4117" },
            { barangay: "Adlas", zipCode: "4117" },
            { barangay: "Anahaw I", zipCode: "4117" },
            { barangay: "Anahaw II", zipCode: "4117" },
            { barangay: "Balite I", zipCode: "4117" },
            { barangay: "Balite II", zipCode: "4117" },
            { barangay: "Balubad", zipCode: "4117" },
            { barangay: "Banaba", zipCode: "4117" },
            { barangay: "Barangay I", zipCode: "4117" },
            { barangay: "Barangay II", zipCode: "4117" },
            { barangay: "Barangay III", zipCode: "4117" },
            { barangay: "Barangay IV", zipCode: "4117" },
            { barangay: "Barangay V", zipCode: "4117" },
            { barangay: "Batas", zipCode: "4117" },
            { barangay: "Biga I", zipCode: "4117" },
            { barangay: "Biga II", zipCode: "4117" },
            { barangay: "Biluso", zipCode: "4117" },
            { barangay: "Bucal", zipCode: "4117" },
            { barangay: "Buho", zipCode: "4117" },
            { barangay: "Bulihan", zipCode: "4117" },
            { barangay: "Cabangaan", zipCode: "4117" },
            { barangay: "Carmen", zipCode: "4117" },
            { barangay: "Hoyo", zipCode: "4117" },
            { barangay: "Hukay", zipCode: "4117" },
            { barangay: "Iba", zipCode: "4117" },
            { barangay: "Inchican", zipCode: "4117" },
            { barangay: "Ipil I", zipCode: "4117" },
            { barangay: "Ipil II", zipCode: "4117" },
            { barangay: "Kalubkob", zipCode: "4117" },
            { barangay: "Kaong", zipCode: "4117" },
            { barangay: "Lalaan I", zipCode: "4117" },
            { barangay: "Lalaan II", zipCode: "4117" },
            { barangay: "Litlit", zipCode: "4117" },
            { barangay: "Lucsuhin", zipCode: "4117" },
            { barangay: "Lumil", zipCode: "4117" },
            { barangay: "Mayumam", zipCode: "4117" },
            { barangay: "Malabag", zipCode: "4117" },
            { barangay: "Malaking Tatyao", zipCode: "4117" },
            { barangay: "Mataas na Burol", zipCode: "4117" },
            { barangay: "Munting Ilog", zipCode: "4117" },
            { barangay: "Narra I", zipCode: "4117" },
            { barangay: "Narra II", zipCode: "4117" },
            { barangay: "Narra III", zipCode: "4117" },
            { barangay: "Paligawan", zipCode: "4117" },
            { barangay: "Pasong Langka", zipCode: "4117" },
            { barangay: "Pooc I", zipCode: "4117" },
            { barangay: "Pooc II", zipCode: "4117" },
            { barangay: "Pulong Bunga", zipCode: "4117" },
            { barangay: "Pulong Saging", zipCode: "4117" },
            { barangay: "Puting Kahoy", zipCode: "4117" },
            { barangay: "Sabutan", zipCode: "4117" },
            { barangay: "San Miguel I", zipCode: "4117" },
            { barangay: "San Miguel II", zipCode: "4117" },
            { barangay: "San Vicente I", zipCode: "4117" },
            { barangay: "San Vicente II", zipCode: "4117" },
            { barangay: "Santol", zipCode: "4117" },
            { barangay: "Tartaria", zipCode: "4117" },
            { barangay: "Tibig", zipCode: "4117" },
            { barangay: "Toledo", zipCode: "4117" },
            { barangay: "Tubuan I", zipCode: "4117" },
            { barangay: "Tubuan II", zipCode: "4117" },
            { barangay: "Tubuan III", zipCode: "4117" },
            { barangay: "Ulat", zipCode: "4117" },
            { barangay: "Yakal", zipCode: "4117" },
        ],
        "General Trias City": [
            { barangay: "Alingaro", zipCode: "4107" },
            { barangay: "Arnaldo Poblacion", zipCode: "4107" },
            { barangay: "Bacao I", zipCode: "4107" },
            { barangay: "Bacao II", zipCode: "4107" },
            { barangay: "Bagumbayan Poblacion", zipCode: "4107" },
            { barangay: "Biclatan, ", zipCode: "4107" },
            { barangay: "Buenavista I", zipCode: "4107" },
            { barangay: "Buenavista II", zipCode: "4107" },
            { barangay: "Buenavista III", zipCode: "4107" },
            { barangay: "Corregidor Poblacion", zipCode: "4107" },
            { barangay: "Dulong Bayan Poblacion", zipCode: "4107" },
            { barangay: "Gov. Ferrer Poblacion", zipCode: "4107" },
            { barangay: "Javalera", zipCode: "4107" },
            { barangay: "Manggahan", zipCode: "4107" },
            { barangay: "Navarro", zipCode: "4107" },
            { barangay: "Ninety Sixth Poblacion", zipCode: "4107" },
            { barangay: "Panungyanan ", zipCode: "4107" },
            { barangay: "Pasong Camachile I", zipCode: "4107" },
            { barangay: "Pasong Camachile II", zipCode: "4107" },
            { barangay: "Pasong Kawayan I", zipCode: "4107" },
            { barangay: "Pasong Kawayan II", zipCode: "4107" },
            { barangay: "Pinagtipunan", zipCode: "4107" },
            { barangay: "Prinza Poblacion", zipCode: "4107" },
            { barangay: "Sampalucan Poblacion", zipCode: "4107" },
            { barangay: "San Francisco", zipCode: "4107" },
            { barangay: "San Gabriel Poblacion", zipCode: "4107" },
            { barangay: "San Juan I", zipCode: "4107" },
            { barangay: "San Juan II", zipCode: "4107" },
            { barangay: "Santa Clara", zipCode: "4107" },
            { barangay: "Santiago", zipCode: "4107" },
            { barangay: "Tapia", zipCode: "4107" },
            { barangay: "Tejero", zipCode: "4107" },
            { barangay: "Vibora Poblacion", zipCode: "4107" },
        ],
        "Amadeo, Cavite": [
            { barangay: "Banaybanay", zipCode: "4119" },
            { barangay: "Barangay I", zipCode: "4119" },
            { barangay: "Barangay II", zipCode: "4119" },
            { barangay: "Barangay III", zipCode: "4119" },
            { barangay: "Barangay IV", zipCode: "4119" },
            { barangay: "Barangay IX", zipCode: "4119" },
            { barangay: "Barangay V", zipCode: "4119" },
            { barangay: "Barangay VI", zipCode: "4119" },
            { barangay: "Barangay VII", zipCode: "4119" },
            { barangay: "Barangay VIII", zipCode: "4119" },
            { barangay: "Barangay X", zipCode: "4119" },
            { barangay: "Barangay XI", zipCode: "4119" },
            { barangay: "Barangay XII", zipCode: "4119" },
            { barangay: "Bucal", zipCode: "4119" },
            { barangay: "Buho", zipCode: "4119" },
            { barangay: "Dagatan ", zipCode: "4119" },
            { barangay: "Halang", zipCode: "4119" },
            { barangay: "Loma ", zipCode: "4119" },
            { barangay: "Maitim I", zipCode: "4119" },
            { barangay: "Maymangga", zipCode: "4119" },
            { barangay: "Minantok Kanluran", zipCode: "4119" },
            { barangay: "Minantok Silangan", zipCode: "4119" },
            { barangay: "Pangil", zipCode: "4119" },
            { barangay: "Salaban", zipCode: "4119" },
            { barangay: "Talon", zipCode: "4119" },
            { barangay: "Tamacan", zipCode: "4119" },
        ],
        "Indang, Cavite": [
            { barangay: "Agus-us", zipCode: "4122" },
            { barangay: "Alulod", zipCode: "4122" },
            { barangay: "Banaba Cerca", zipCode: "4122" },
            { barangay: "Banaba Lejos", zipCode: "4122" },
            { barangay: "Bancod", zipCode: "4122" },
            { barangay: "Barangay 1", zipCode: "4122" },
            { barangay: "Barangay 2", zipCode: "4122" },
            { barangay: "Barangay 3", zipCode: "4122" },
            { barangay: "Barangay 4", zipCode: "4122" },
            { barangay: "Buna Cerca", zipCode: "4122" },
            { barangay: "Buna Lejos I", zipCode: "4122" },
            { barangay: "Buna Lejos II", zipCode: "4122" },
            { barangay: "Calumpang Cerca", zipCode: "4122" },
            { barangay: "Calumpang Lejos I", zipCode: "4122" },
            { barangay: "Carasuchi", zipCode: "4122" },
            { barangay: "Daine I", zipCode: "4122" },
            { barangay: "Daine II", zipCode: "4122" },
            { barangay: "Guyam Malaki", zipCode: "4122" },
            { barangay: "Guyam Munti", zipCode: "4122" },
            { barangay: "Harasan", zipCode: "4122" },
            { barangay: "Kayquit I", zipCode: "4122" },
            { barangay: "Kayquit II", zipCode: "4122" },
            { barangay: "Kayquit III", zipCode: "4122" },
            { barangay: "Kaytambog", zipCode: "4122" },
            { barangay: "Kaytapos", zipCode: "4122" },
            { barangay: "Limbon", zipCode: "4122" },
            { barangay: "Lumampong Balagbag", zipCode: "4122" },
            { barangay: "Lumampong Halayhay", zipCode: "4122" },
            { barangay: "Mahabangkahoy Cerca", zipCode: "4122" },
            { barangay: "Mahabangkahoy Lejos", zipCode: "4122" },
            { barangay: "Mataas na Lupa", zipCode: "4122" },
            { barangay: "Pulo", zipCode: "4122" },
            { barangay: "Tambo Balagbag", zipCode: "4122" },
            { barangay: "Tambo Ilaya", zipCode: "4122" },
            { barangay: "Tambo Kulit", zipCode: "4122" },
            { barangay: "Tambo Malaki", zipCode: "4122" },
        ],
        "Tanza, Cavite": [
            { barangay: "Amaya I", zipCode: "4108" },
            { barangay: "Amaya II", zipCode: "4108" },
            { barangay: "Amaya III", zipCode: "4108" },
            { barangay: "Amaya IV", zipCode: "4108" },
            { barangay: "Amaya V", zipCode: "4108" },
            { barangay: "Amaya VI", zipCode: "4108" },
            { barangay: "Amaya VII", zipCode: "4108" },
            { barangay: "Bagtas", zipCode: "4108" },
            { barangay: "Barangay I", zipCode: "4108" },
            { barangay: "Barangay II", zipCode: "4108" },
            { barangay: "Barangay III", zipCode: "4108" },
            { barangay: "Barangay IV", zipCode: "4108" },
            { barangay: "Biga", zipCode: "4108" },
            { barangay: "Biwas", zipCode: "4108" },
            { barangay: "Bucal", zipCode: "4108" },
            { barangay: "Bunga", zipCode: "4108" },
            { barangay: "Calibuyo", zipCode: "4108" },
            { barangay: "Capipisa", zipCode: "4108" },
            { barangay: "Daang Amaya I", zipCode: "4108" },
            { barangay: "Daang Amaya II", zipCode: "4108" },
            { barangay: "Daang Amaya III", zipCode: "4108" },
            { barangay: "Halayhay", zipCode: "4108" },
            { barangay: "Julugan I", zipCode: "4108" },
            { barangay: "Julugan II", zipCode: "4108" },
            { barangay: "Julugan III", zipCode: "4108" },
            { barangay: "Julugan IV", zipCode: "4108" },
            { barangay: "Julugan V", zipCode: "4108" },
            { barangay: "Julugan VI", zipCode: "4108" },
            { barangay: "Julugan VII", zipCode: "4108" },
            { barangay: "Julugan VIII", zipCode: "4108" },
            { barangay: "Lambingan", zipCode: "4108" },
            { barangay: "Mulawin", zipCode: "4108" },
            { barangay: "Paradahan I", zipCode: "4108" },
            { barangay: "Paradahan II", zipCode: "4108" },
            { barangay: "Punta I", zipCode: "4108" },
            { barangay: "Punta II", zipCode: "4108" },
            { barangay: "Sahud Ulan", zipCode: "4108" },
            { barangay: "Sanja Mayor", zipCode: "4108" },
            { barangay: "Santol", zipCode: "4108" },
            { barangay: "Tanauan", zipCode: "4108" },
            { barangay: "Tres Cruses", zipCode: "4108" },
        ],
        "Tagaytay, Cavite": [
            { barangay: "Asisan", zipCode: "4120" },
            { barangay: "Bagong Tubig", zipCode: "4120" },
            { barangay: "Calabuso", zipCode: "4120" },
            { barangay: "Dapdap East", zipCode: "4120" },
            { barangay: "Dapdap West", zipCode: "4120" },
            { barangay: "Francisco", zipCode: "4120" },
            { barangay: "Guinhawa North", zipCode: "4120" },
            { barangay: "Guinhawa South", zipCode: "4120" },
            { barangay: "Iruhin East", zipCode: "4120" },
            { barangay: "Iruhin South", zipCode: "4120" },
            { barangay: "Iruhin West", zipCode: "4120" },
            { barangay: "Kaybagal East", zipCode: "4120" },
            { barangay: "Kaybagal North", zipCode: "4120" },
            { barangay: "Kaybagal South", zipCode: "4120" },
            { barangay: "Mag-Asawang Ilat", zipCode: "4120" },
            { barangay: "Maharlika East", zipCode: "4120" },
            { barangay: "Maharlika West", zipCode: "4120" },
            { barangay: "Maitim 2nd Central", zipCode: "4120" },
            { barangay: "Maitim 2nd East", zipCode: "4120" },
            { barangay: "Maitim 2nd West", zipCode: "4120" },
            { barangay: "Mendez Crossing East", zipCode: "4120" },
            { barangay: "Mendez Crossing West", zipCode: "4120" },
            { barangay: "Neogan", zipCode: "4120" },
            { barangay: "Patutong Malaki North", zipCode: "4120" },
            { barangay: "Patutong Malaki South", zipCode: "4120" },
            { barangay: "Sambong", zipCode: "4120" },
            { barangay: "San Jose", zipCode: "4120" },
            { barangay: "Silang Junction North", zipCode: "4120" },
            { barangay: "Silang Junction South", zipCode: "4120" },
            { barangay: "Sungay North", zipCode: "4120" },
            { barangay: "Sungay South", zipCode: "4120" },
            { barangay: "Tolentino East", zipCode: "4120" },
            { barangay: "Tolentino West", zipCode: "4120" },
            { barangay: "Zambal", zipCode: "4120" },
        ],
        "Alfonso, Cavite": [
            { barangay: "Amuyong", zipCode: "4123" },
            { barangay: "Barangay I", zipCode: "4123" },
            { barangay: "Barangay II", zipCode: "4123" },
            { barangay: "Barangay III", zipCode: "4123" },
            { barangay: "Barangay IV", zipCode: "4123" },
            { barangay: "Barangay V", zipCode: "4123" },
            { barangay: "Bilog", zipCode: "4123" },
            { barangay: "Buck Estate", zipCode: "4123" },
            { barangay: "Esperanza Ibaba", zipCode: "4123" },
            { barangay: "Esperanza Ilaya", zipCode: "4123" },
            { barangay: "Kaysuyo", zipCode: "4123" },
            { barangay: "Kaytitinga I", zipCode: "4123" },
            { barangay: "Kaytitinga II", zipCode: "4123" },
            { barangay: "Kaytitinga III", zipCode: "4123" },
            { barangay: "Luksuhin", zipCode: "4123" },
            { barangay: "Luksuhin Ilaya", zipCode: "4123" },
            { barangay: "Mangas I", zipCode: "4123" },
            { barangay: "Mangas II", zipCode: "4123" },
            { barangay: "Marahan I", zipCode: "4123" },
            { barangay: "Marahan II", zipCode: "4123" },
            { barangay: "Matagbak I", zipCode: "4123" },
            { barangay: "Matagbak II", zipCode: "4123" },
            { barangay: "Pajo", zipCode: "4123" },
            { barangay: "Palumlum", zipCode: "4123" },
            { barangay: "Santa Teresa", zipCode: "4123" },
            { barangay: "Sikat", zipCode: "4123" },
            { barangay: "Sinaliw Malaki", zipCode: "4123" },
            { barangay: "Sinaliw na Munti", zipCode: "4123" },
            { barangay: "Sulsugin", zipCode: "4123" },
            { barangay: "Taywanak Ibaba", zipCode: "4123" },
            { barangay: "Taywanak Ilaya", zipCode: "4123" },
            { barangay: "Upli", zipCode: "4123" },
        ],
        "General Emilio Aguinaldo, Cavite": [
            { barangay: "A. Dalusag", zipCode: "4124" },
            { barangay: "Batas Dao", zipCode: "4124" },
            { barangay: "Castaños Cerca", zipCode: "4124" },
            { barangay: "Castaños Lejos", zipCode: "4124" },
            { barangay: "Kabulusan", zipCode: "4124" },
            { barangay: "Kaymisas", zipCode: "4124" },
            { barangay: "Kaypaaba", zipCode: "4124" },
            { barangay: "Lumipa", zipCode: "4124" },
            { barangay: "Narvaez", zipCode: "4124" },
            { barangay: "Poblacion I", zipCode: "4124" },
            { barangay: "Poblacion II", zipCode: "4124" },
            { barangay: "Poblacion III", zipCode: "4124" },
            { barangay: "Poblacion IV", zipCode: "4124" },
            { barangay: "Tabora", zipCode: "4124" },
        ],
        "Magallanes, Cavite": [
            { barangay: "Baliwag", zipCode: "4113" },
            { barangay: "Barangay 1", zipCode: "4113" },
            { barangay: "Barangay 2", zipCode: "4113" },
            { barangay: "Barangay 3", zipCode: "4113" },
            { barangay: "Barangay 4", zipCode: "4113" },
            { barangay: "Barangay 5", zipCode: "4113" },
            { barangay: "Bendita I", zipCode: "4113" },
            { barangay: "Bendita II", zipCode: "4113" },
            { barangay: "Caluangan", zipCode: "4113" },
            { barangay: "Kabulusan", zipCode: "4113" },
            { barangay: "Medina", zipCode: "4113" },
            { barangay: "Pacheco", zipCode: "4113" },
            { barangay: "Ramirez", zipCode: "4113" },
            { barangay: "San Agustin", zipCode: "4113" },
            { barangay: "Tua", zipCode: "4113" },
            { barangay: "Urdaneta", zipCode: "4113" },
        ],
        "Maragondon, Cavite": [
            { barangay: "Bucal I", zipCode: "4112" },
            { barangay: "Bucal II", zipCode: "4112" },
            { barangay: "Bucal III - A", zipCode: "4112" },
            { barangay: "Bucal III - B", zipCode: "4112" },
            { barangay: "Bucal IV - A", zipCode: "4112" },
            { barangay: "Bucal IV - B", zipCode: "4112" },
            { barangay: "Caingin Poblacion", zipCode: "4112" },
            { barangay: "Garita I A", zipCode: "4112" },
            { barangay: "Garita I B", zipCode: "4112" },
            { barangay: "Layong Mabilog", zipCode: "4112" },
            { barangay: "Mabato", zipCode: "4112" },
            { barangay: "Pantihan I", zipCode: "4112" },
            { barangay: "Pantihan II", zipCode: "4112" },
            { barangay: "Pantihan III", zipCode: "4112" },
            { barangay: "Pantihan IV", zipCode: "4112" },
            { barangay: "Patungan", zipCode: "4112" },
            { barangay: "Pinagsanhan I A", zipCode: "4112" },
            { barangay: "Pinagsanhan I B", zipCode: "4112" },
            { barangay: "Poblacion I A", zipCode: "4112" },
            { barangay: "Poblacion I B", zipCode: "4112" },
            { barangay: "Poblacion II A", zipCode: "4112" },
            { barangay: "Poblacion II B", zipCode: "4112" },
            { barangay: "San Miguel I A", zipCode: "4112" },
            { barangay: "San Miguel I B", zipCode: "4112" },
            { barangay: "Talipusngo", zipCode: "4112" },
            { barangay: "Tulay Kanluran", zipCode: "4112" },
            { barangay: "Tulay Silangan", zipCode: "4112" },
        ],
        "Mendez, Cavite": [
            { barangay: "Anuling Cerca I", zipCode: "4121" },
            { barangay: "Anuling Cerca II", zipCode: "4121" },
            { barangay: "Anuling Lejos I", zipCode: "4121" },
            { barangay: "Anuling Lejos II", zipCode: "4121" },
            { barangay: "Asis I", zipCode: "4121" },
            { barangay: "Asis II", zipCode: "4121" },
            { barangay: "Asis III", zipCode: "4121" },
            { barangay: "Banayad", zipCode: "4121" },
            { barangay: "Bukal", zipCode: "4121" },
            { barangay: "Galicia I", zipCode: "4121" },
            { barangay: "Galicia II", zipCode: "4121" },
            { barangay: "Galicia III", zipCode: "4121" },
            { barangay: "Miguel Mojica", zipCode: "4121" },
            { barangay: "Palocpoc I", zipCode: "4121" },
            { barangay: "Palocpoc II", zipCode: "4121" },
            { barangay: "Panungyan I", zipCode: "4121" },
            { barangay: "Panungyan II", zipCode: "4121" },
            { barangay: "Poblacion I", zipCode: "4121" },
            { barangay: "Poblacion II", zipCode: "4121" },
            { barangay: "Poblacion III", zipCode: "4121" },
            { barangay: "Poblacion IV", zipCode: "4121" },
            { barangay: "Poblacion VI", zipCode: "4121" },
            { barangay: "Poblacion VII", zipCode: "4121" },
        ],
        "Naic, Cavite": [
            { barangay: "Bagong Karsada", zipCode: "4110" },
            { barangay: "Balsahan", zipCode: "4110" },
            { barangay: "Bancaan", zipCode: "4110" },
            { barangay: "Bucana Malaki", zipCode: "4110" },
            { barangay: "Bucana Sasahan", zipCode: "4110" },
            { barangay: "Calubcob", zipCode: "4110" },
            { barangay: "Capt. C. Nazareno", zipCode: "4110" },
            { barangay: "Gomez-Zamora", zipCode: "4110" },
            { barangay: "Halang", zipCode: "4110" },
            { barangay: "Humbac", zipCode: "4110" },
            { barangay: "Ibayo Estacion", zipCode: "4110" },
            { barangay: "Ibayo Silangan", zipCode: "4110" },
            { barangay: "Kanluran", zipCode: "4110" },
            { barangay: "Labac", zipCode: "4110" },
            { barangay: "Latoria", zipCode: "4110" },
            { barangay: "Mabolo", zipCode: "4110" },
            { barangay: "Makina", zipCode: "4110" },
            { barangay: "Malainen Bago", zipCode: "4110" },
            { barangay: "Malainen Luma", zipCode: "4110" },
            { barangay: "Molino", zipCode: "4110" },
            { barangay: "Munting Mapino", zipCode: "4110" },
            { barangay: "Muzon", zipCode: "4110" },
            { barangay: "Palangue 1", zipCode: "4110" },
            { barangay: "Palangue 2 & 3", zipCode: "4110" },
            { barangay: "Sabang", zipCode: "4110" },
            { barangay: "San Roque", zipCode: "4110" },
            { barangay: "Santulan", zipCode: "4110" },
            { barangay: "Sapa", zipCode: "4110" },
            { barangay: "Timalan Balsahan", zipCode: "4110" },
            { barangay: "Timalan Concepcion", zipCode: "4110" },
        ],
        "Ternate, Cavite": [
            { barangay: "", zipCode: "" },
            { barangay: "Bucana", zipCode: "4111" },
            { barangay: "Poblacion I", zipCode: "4111" },
            { barangay: "Poblacion II", zipCode: "4111" },
            { barangay: "Poblacion III", zipCode: "4111" },
            { barangay: "San Jose", zipCode: "4111" },
            { barangay: "San Jose I", zipCode: "4111" },
            { barangay: "San Jose II", zipCode: "4111" },
            { barangay: "Sapang I", zipCode: "4111" },
            { barangay: "Sapang II", zipCode: "4111" },
        ],
    };

    function populateBarangays() {
        const selectedCity = document.getElementById('inputCity').value;
        const barangaySelect = document.getElementById('barangay');
        const zipCodeInput = document.getElementById('zip_code');

        barangaySelect.innerHTML = ""; // Clear existing options

        if (selectedCity in barangaysData) {
            const barangays = barangaysData[selectedCity];
            barangays.forEach(({ barangay }) => {
                const option = document.createElement('option');
                option.value = barangay;
                option.textContent = barangay;
                barangaySelect.appendChild(option);
            });
        } else {
            // Add default option if no barangays are available for the selected city
            const defaultOption = document.createElement('option');
            defaultOption.value = "";
            defaultOption.textContent = "Select Barangay";
            barangaySelect.appendChild(defaultOption);
        }
    }

    function updateZipCode() {
    const selectedCity = document.getElementById('inputCity').value;
    const selectedBarangay = document.getElementById('barangay').value;
    const zipCodeInput = document.getElementById('zip_code');

    if (selectedBarangay.html === "") {
        // Clear ZIP code input if barangay is not selected
        zipCodeInput.value = "";
    }
    else if (selectedCity in barangaysData) {
        const barangays = barangaysData[selectedCity];
        const selectedBarangayData = barangays.find(({ barangay }) => barangay === selectedBarangay);
        if (selectedBarangayData) {
            zipCodeInput.value = selectedBarangayData.zipCode;
        } else {
            zipCodeInput.value = "";
        }
    } else {
        zipCodeInput.value = "";
    }
}



    // Attach event listener to the city select dropdown to trigger functions on change
    document.getElementById('inputCity').addEventListener('change', () => {
        populateBarangays();
    });
    document.getElementById('barangay').addEventListener('change', () => {
        updateZipCode();
    });

    // Initial call to populateBarangays to populate barangay options for the default selected city
    populateBarangays();
